### ISSUE TITLE
Can you share your resume?

### ISSUE THREAD

**Issue by Sarthaknegigit** [swarajpande4/swarajpande4#3]
Hey Swaraj, Sarthak this side.
Congratulations on getting an internship opportunity in RedHat.
Can you please share the resume that helped you getting this one?

**Comment by swarajpande5** [comment]
Thanks, 
Sure I have just sent it to you on your email (snegicodes@gmail.com)

**Comment by Sarthaknegigit** [comment]
Thanks Buddy <3
